---

- name: Install packages for AP mode
  ansible.builtin.apt:
    pkg: '{{ item }}'
    state: 'present'
    autoremove: 'yes'
  with_items:
    - 'iptables-persistent'
    - 'hostapd'
    - 'dnsmasq'
  register: access_point_mode_packages_installed
  until: access_point_mode_packages_installed is succeeded

- name: Configure dhcpcd with static IP address
  ansible.builtin.blockinfile:
    path: '/etc/dhcpcd.conf'
    block: |
      interface {{ moodlebox_wifi_sta_interface }}
      # Uncomment following line to disable AP+STA mode
      # nohook wpa_supplicant

      interface {{ moodlebox_wifi_ap_interface }}
      static ip_address={{ moodlebox_ip_address | ansible.utils.ipaddr('host') }}
      nohook wpa_supplicant
  notify:
    - Restart networking

- name: Update access point configuration file
  ansible.builtin.template:
    src: 'etc/hostapd/hostapd.conf.j2'
    dest: '/etc/hostapd/hostapd.conf'
    mode: '0644'
  notify:
    - Restart networking

- name: Update access point settings
  ansible.builtin.lineinfile:
    path: '/etc/default/hostapd'
    regexp: '^#?DAEMON_CONF'
    line: 'DAEMON_CONF="/etc/hostapd/hostapd.conf"'
  notify:
    - Restart networking

- name: Unmask, enable and start hostapd
  ansible.builtin.systemd:
    name: 'hostapd'
    state: 'started'
    enabled: 'yes'
    masked: 'no'

- name: Update dnsmasq configuration
  ansible.builtin.template:
    src: 'etc/dnsmasq.conf.j2'
    dest: '/etc/dnsmasq.conf'
    mode: '0664'
  notify:
    - Restart networking

- name: Update dnsmasq service file
  ansible.builtin.blockinfile:
    path: '/lib/systemd/system/dnsmasq.service'
    insertbefore: '^\[Install\]\s*$'
    block: |
      RestartSec=5
      Restart=on-failure
  notify:
    - Restart networking

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
