# invoke with: ansible-playbook moodlebox.yml
# on macOS with ansible 2.3.1 and later, you have to install sshpass:
#   brew tap esolitos/ipa
#   brew install sshpass
---

- name: Include playbook to install SSH keys
  ansible.builtin.import_playbook: installsshkeys.yml

- name: Include playbook to build MoodleBox
  ansible.builtin.import_playbook: buildmoodlebox.yml
