---

- name: Uninstall useless packages
  ansible.builtin.apt:
    pkg: '{{ packages_to_uninstall }}'
    state: 'absent'
    purge: 'yes'
  when: 'packages_to_uninstall is defined'
  register: packages_uninstalled
  until: packages_uninstalled is succeeded

- name: Install packages
  ansible.builtin.apt:
    pkg: '{{ packages_to_install }}'
    state: 'present'
    autoremove: 'yes'
  when: 'packages_to_install is defined'
  register: packages_installed
  until: packages_installed is succeeded
