---

- name: Uninstall useless packages
  ansible.builtin.apt:
    pkg: '{{ moodlebox_uninstall_packages }}'
    state: 'absent'
    purge: 'yes'
  when: 'moodlebox_uninstall_packages is defined'
  register: packages_uninstalled
  until: packages_uninstalled is succeeded

- name: Install packages
  ansible.builtin.apt:
    pkg: '{{ moodlebox_install_packages }}'
    state: 'present'
    autoremove: 'yes'
  when: 'moodlebox_install_packages is defined'
  register: packages_installed
  until: packages_installed is succeeded
