---

- name: Update apt cache and upgrade
  ansible.builtin.apt:
    update_cache: 'yes'
    upgrade: 'dist'
    autoclean: 'yes'
    autoremove: 'yes'
  register: apt_upgrade
  until: apt_upgrade is succeeded
