---

- name: Update wifi client configuration file 'wpa_supplicant.conf'
  ansible.builtin.template:
    src: 'etc/wpa_supplicant/wpa_supplicant.conf.j2'
    dest: '/etc/wpa_supplicant/wpa_supplicant.conf'
    mode: '0644'
  notify:
    - Restart networking

- name: Get rfkill files
  ansible.builtin.find:
    paths: '/var/lib/systemd/rfkill'
    patterns: '*:wlan'
  register: rfkill_wlan

- name: Unblock wifi, since wifi country is set
  ansible.builtin.copy:
    dest: '{{ item.path }}'
    content: '0'
    mode: '0644'
  with_items: '{{ rfkill_wlan.files }}'
  notify:
    - Restart networking

- name: Disable unused wpa_supplicant service
  ansible.builtin.systemd:
    name: 'wpa_supplicant'
    state: 'stopped'
    enabled: 'no'
    masked: 'no'

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
