---

- name: Install MariaDB
  ansible.builtin.apt:
    pkg: 'mariadb-server'
    state: 'present'
  register: database_install_mariadb
  until: database_install_mariadb is succeeded

- name: Install python3-pymysql
  ansible.builtin.apt:
    pkg: 'python3-pymysql'
    state: 'present'
  register: database_pymysql_installed
  until: database_pymysql_installed is succeeded

- name: Add MariaDB user with all privileges
  community.mysql.mysql_user:
    name: '{{ moodlebox_db_username }}'
    password: '{{ moodlebox_db_password }}'
    login_unix_socket: '/var/run/mysqld/mysqld.sock'
    priv: '*.*:ALL,GRANT'
  no_log: true

- name: Update MariaDB settings
  ansible.builtin.copy:
    src: 'etc/mysql/mariadb.conf.d/50-server.cnf'
    dest: '/etc/mysql/mariadb.conf.d/50-server.cnf'
    mode: '0644'

- name: Restart MariaDB database
  ansible.builtin.systemd:
    name: 'mariadb'
    state: 'restarted'
