---

- name: reduce memory split down to 16Mb, as we are on a headless system
  ansible.builtin.lineinfile:
    path: '/boot/config.txt'
    line: 'gpu_mem=16'
    insertafter: '^\[all\]'
    firstmatch: true
  notify:
    - reboot box

- name: enable shutdown/startup hardware button
  ansible.builtin.lineinfile:
    path: '/boot/config.txt'
    line: 'dtoverlay=gpio-shutdown'
    insertafter: '^# Additional overlays and parameters'
  notify:
    - reboot box

- name: copy udev rule to add wireless interface for AP mode
  ansible.builtin.template:
    src: 'etc/udev/rules.d/90-wireless.rules.j2'
    dest: '/etc/udev/rules.d/90-wireless.rules'
    mode: '0644'
  notify:
    - reboot box

- name: flush handlers
  ansible.builtin.meta: flush_handlers
