---

- name: Reduce memory split down to 16Mb, as we are on a headless system
  ansible.builtin.lineinfile:
    path: '/boot/config.txt'
    line: 'gpu_mem=16'
    insertafter: '^\[all\]'
    firstmatch: true
  notify:
    - Reboot box

- name: Enable shutdown/startup hardware button
  ansible.builtin.lineinfile:
    path: '/boot/config.txt'
    line: 'dtoverlay=gpio-shutdown'
    insertafter: '^# Additional overlays and parameters'
  notify:
    - Reboot box

- name: Copy udev rule to add wireless interface for AP mode
  ansible.builtin.template:
    src: 'etc/udev/rules.d/90-wireless.rules.j2'
    dest: '/etc/udev/rules.d/90-wireless.rules'
    mode: '0644'
  notify:
    - Reboot box

- name: Add script to fix hostname at the very first boot
  ansible.builtin.template:
    src: 'etc/init.d/fix_hostname_once.j2'
    dest: '/etc/init.d/fix_hostname_once'
    mode: '0755'

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
