---

- name: Set moodleinstall_config_cmd variable
  ansible.builtin.set_fact:
    moodleinstall_config_cmd: '/usr/bin/php {{ moodlebox_moodle_source_dir }}/admin/cli/cfg.php'

- name: Configure Moodle site summary
  ansible.builtin.import_tasks: summary.yml

- name: Get Moodle and install it
  ansible.builtin.import_tasks: coreinstall.yml

- name: Get MoodleBox plugin and install it
  ansible.builtin.import_tasks: moodleboxplugin.yml

- name: Install MathJax library
  ansible.builtin.import_tasks: mathjax.yml

- name: Configure additional Moodle settings
  ansible.builtin.import_tasks: moodleconfig.yml
