---

- name: Format release date using locales
  ansible.builtin.command:
    cmd: >
      date --date={{ moodlebox_release_date }} '+%-d %B %Y'
  environment:
    LC_ALL: '{{ item.1 }}'
  with_indexed_items: '{{ moodlebox_locales }}'
  when: 'dates_formatted is not defined or item.0 < moodlebox_locales|length'
  register: dates_formatted
  changed_when: dates_formatted.rc == 0

- name: Set vars with formatted dates
  ansible.builtin.set_fact:
    '{{ item.0 | regex_replace("^(.*)_.*UTF-8$", "moodlebox_release_date_\1") }}': '{{ item.1.stdout }}'
  # noqa var-naming
  # var name is valid after regex replacement
  with_together:
    - '{{ moodlebox_locales }}'
    - '{{ dates_formatted.results }}'

- name: Set summary string with formatted dates
  ansible.builtin.set_fact:
    moodlebox_moodle_summary: '{{ moodlebox_moodle_summary }}'
