---

- name: check if database for Moodle exists
  ansible.builtin.command: mysql -e 'SHOW DATABASES LIKE "{{ moodlebox_moodle_db }}"' -sN
  register: moodle_db_exists
  failed_when: moodle_db_exists.rc > 1
  changed_when: moodle_db_exists.stdout | length > 0
  notify: drop database for Moodle

- name: remove temporary storage for Moodle cache
  ansible.posix.mount:
    name: '{{ item.name }}'
    state: 'unmounted'
  with_items:
    - { name: '/var/cache/moodle' }
    - { name: '{{ moodlebox_moodle_data_dir }}/temp' }
    - { name: '{{ moodlebox_moodle_data_dir }}/sessions' }

- name: remove previous Moodle installation data
  ansible.builtin.file:
    path: '{{ item }}'
    state: 'absent'
  with_items:
    - '{{ moodlebox_moodle_data_dir }}'
    - '{{ moodlebox_moodle_source_dir }}/config.php'
    - '/var/cache/moodle'
    - '/var/cache/moodle-cache-backup'

- name: set default direvent configuration
  ansible.builtin.copy:
    dest: '/etc/direvent.conf'
    content: |
      # This is the configuration file for direvent. Read
      # direvent.conf(5) for more information about how to
      # fill this file.
      #
    mode: '0644'

- name: flush handlers
  ansible.builtin.meta: flush_handlers
