---

- name: update .bashrc file (1)
  ansible.builtin.lineinfile:
    path: '/home/{{ moodlebox_username }}/.bashrc'
    regexp: '^    PS1=.*01;32m.*01;34m.*$'
    line: '    PS1="${debian_chroot:+($debian_chroot)}\[\\e[0;93m\]\\u\[\\e[0m\]@\[\\e[38;5;125m\]\\h\[\\e[0m\]:\[\\e[0;96m\]\\w \[\\e[0m\]\$ "'
    insertafter: '^if \[ "\$color_prompt" = yes \]; then'
    backrefs: 'yes'

- name: update .bashrc file (2)
  ansible.builtin.blockinfile:
    path: '/home/{{ moodlebox_username }}/.bashrc'
    block: |
      alias l='ls -lh'
      alias ll='ls -lAh'

      # Assign arrow keys to history search in bash
      bind '"\e[A":history-search-backward'
      bind '"\e[B":history-search-forward'
      # TAB cycles through the list of partial matches
      bind 'TAB:menu-complete'

# disable autologin, step 1
- name: change default target to multi-user.target
  ansible.builtin.file:
    src: '/usr/lib/systemd/system/multi-user.target'
    path: '/etc/systemd/system/default.target'
    state: link

# disable autologin, step 2
- name: remove `autologin.conf` file
  ansible.builtin.file:
    path: '/etc/systemd/system/getty@tty1.service.d/autologin.conf'
    state: absent
