---
- name: configure zeroconf service
  ansible.builtin.template:
    src: 'etc/avahi/services/moodlebox.service.j2'
    dest: '/etc/avahi/services/{{ moodlebox_hostname }}.service'
    mode: '0644'
  register: network_configured
  notify: restart networking

- name: flush handlers
  ansible.builtin.meta: flush_handlers
