---

- name: Set timezone
  ansible.builtin.file:
    src: '/usr/share/zoneinfo/{{ moodlebox_timezone }}'
    path: '/etc/localtime'
    state: 'link'
  register: timezone_status
  notify:
    - Update tzdata

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
