---

- name: reboot box
  ansible.builtin.reboot:

- name: restart networking
  ansible.builtin.systemd:
    name: 'networking'
    state: 'restarted'

- name: restart web services
  ansible.builtin.systemd:
    name: '{{ item }}'
    state: 'restarted'
    daemon_reload: 'yes'
  with_items:
    - 'nginx'
    - 'php7.4-fpm'

- name: restart direvent
  ansible.builtin.systemd:
    name: 'direvent'
    state: 'restarted'
