---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 4 * * 0"

defaults:
  run:
    working-directory: 'moodlebox'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'moodlebox'

      - name: Check code syntax.
        run: |
          ansible-playbook moodlebox.yml --syntax-check -vvv
          git ls-files '*.yaml' '*.yml' | xargs yamllint
#         git ls-files *yml roles/ vars/ tests/  | xargs ansible-review
#         git diff master | ansible-review

      - name: Lint code
        uses: ansible/ansible-lint-action@master
        with:
          targets: 'moodlebox.yml'
