name: CI
'on':
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 4 * * 0"

defaults:
  run:
    working-directory: 'moodlebox'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'moodlebox'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install yamllint ansible-lint

      - name: Lint code.
        run: |
          ansible-playbook moodlebox.yml --syntax-check -vvv
          ansible-lint -p moodlebox.yml
          git ls-files '*.yaml' '*.yml' | xargs yamllint
#         git ls-files *yml roles/ vars/ tests/  | xargs ansible-review
#         git diff master | ansible-review
