---
name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * 0'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      # Important: This sets up GITHUB_WORKSPACE environment variable
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Check code syntax.
        run: |
          ansible-playbook moodlebox.yml --syntax-check -vvv
          git ls-files '*.yaml' '*.yml' | xargs yamllint
#         git ls-files *yml roles/ vars/ tests/  | xargs ansible-review
#         git diff master | ansible-review

      - name: Lint code
        uses: ansible/ansible-lint-action@master
        with:
          targets: 'moodlebox.yml'
          override-deps: |
            ansible-lint==5.3.2
